<html xmlns="http://www.w3.org/1999/xhtml">

  <head>

<!-- If you delete this meta tag, the ground will open and swallow you. -->

    <meta name="viewport" content="width=device-width" />

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <title>Contato</title>

  </head>

  <body bgcolor="#FFFFFF" topmargin="0" leftmargin="0" marginheight="0" marginwidth="0" style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;-webkit-font-smoothing: antialiased;-webkit-text-size-adjust: none;width: 100% !important;height: 100%">



        <!-- HEADER -->

        <table width="37%" bgcolor="#f2f2f2" class="head-wrap" style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;width: 100%"><tr style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif"><td bgcolor="#FFFFFF" style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif">
          
          
          
          <!-- /content -->
          
          <div class="content" style="margin: 0 auto;padding: 15px;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;max-width: 600px;display: block">
            
            <table width="49%" align="center" style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;width: 100%"><tr style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif"><td width="59%" height="88" bgcolor="#FFFFFF" style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif">
              <img src="http://<?php echo $_SERVER['HTTP_HOST'];?>/assets/images/pig.png" width="300" height="180" style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;max-width: 100%" /></td>
              
              <td width="41%" align="right" bgcolor="#FFFFFF" style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif"><h6 class="collapse" style="margin: 0 !important;padding: 0;font-family: &quot;HelveticaNeue-Light&quot;, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif;line-height: 1.1;margin-bottom: 15px;color: #004581;font-weight: 900;font-size: 14px;text-transform: uppercase">&nbsp;</h6></td>
              
          </tr></table></div><!-- /content -->
          
          
          
        </td>

</tr></table><!-- /HEADER --><!-- BODY --><table class="body-wrap" bgcolor="" style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;width: 100%"><tr style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif"><td width="5%" bgcolor="#FFFFFF" style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif"></td>

                <td width="90%" align="" bgcolor="#FFFFFF" class="container" style="margin: 0 auto !important;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;display: block !important;max-width: 600px !important;clear: both !important">



                    <!-- content -->

                  <div class="content" style="margin: 0 auto;padding: 15px;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;max-width: 600px;display: block">

                        <table style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;width: 100%"><tr style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif">
                          <td style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif">


                        <div align="center"><strong>COTA&Ccedil;&Atilde;O:</strong></div></td>

                            </tr></table></div><!-- /content -->



                    <!-- content -->

                    <div class="content" style="margin: 0 auto;padding: 15px;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;max-width: 600px;display: block">



                        <table bgcolor="" style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;width: 100%"><tr style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif">
                          <td style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif"><div align="left">
                  <table width="527" height="101" border="0" align="center">
                                        <tr>
                                          <td width="91"><strong>Nome:</strong></td>
                                          <td width="426"><span style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;margin-bottom: 10px;font-weight: normal;font-size: 14px;line-height: 1.8;text-align: justify;     text-indent: 35px;
    color: #564F4F;"><?php echo  utf8_decode($this->dados['nome']); ?></span></td>
                                        </tr>
                                        <tr>
                                          <td><strong>E-mail:</strong></td>
                                          <td><span style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;margin-bottom: 10px;font-weight: normal;font-size: 14px;line-height: 1.8;text-align: justify;     text-indent: 35px;
    color: #564F4F;"><?php echo $this->dados['email']; ?></span></td>
                                        </tr>
                                        <tr>
                                          <td><strong>Telefone:</strong></td>
                                          <td><div align="left"><span style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;margin-bottom: 10px;font-weight: normal;font-size: 14px;line-height: 1.8;text-align: justify;     text-indent: 35px;
    color: #564F4F;"><?php echo  utf8_decode($this->dados['assunto']); ?></span></div></td>
                                        </tr>
                                        <tr>
                                          <td><strong>Empresa:</strong></td>
                                          <td><span style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;margin-bottom: 10px;font-weight: normal;font-size: 14px;line-height: 1.6"><?php echo  utf8_decode($this->dados['empresa']); ?></span></td>
                                        </tr>
                                        <tr>
                                          <td><strong>CNPJ:</strong></td>
                                          <td><span style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;margin-bottom: 10px;font-weight: normal;font-size: 14px;line-height: 1.6"><?php echo $this->dados['cnpj']; ?></span></td>
                                        </tr>
                                        <tr>
                                          <td><strong>I.E:</strong></td>
                                          <td><span style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;margin-bottom: 10px;font-weight: normal;font-size: 14px;line-height: 1.6"><?php echo $this->dados['ie']; ?></span></td>
                                        </tr>
                                        <tr>
                                          <td><strong>Produto:</strong></td>
                                          <td><span style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;margin-bottom: 10px;font-weight: normal;font-size: 14px;line-height: 1.6"><?php echo  utf8_decode($this->dados['tipo_carga']); ?></span></td>
                                        </tr>
                                        <tr>
                                          <td><strong>Quantidade:</strong></td>
                                          <td><span style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;margin-bottom: 10px;font-weight: normal;font-size: 14px;line-height: 1.6"><?php echo  $this->dados['quantidade']; ?></span></td>
                                        </tr>
                                        <tr>
                                          <td><strong>Origem:</strong></td>
                                          <td><span style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;margin-bottom: 10px;font-weight: normal;font-size: 14px;line-height: 1.6"><?php echo utf8_decode($this->dados['origem']); ?></span></td>
                                        </tr>
                                        <tr>
                                          <td><strong>Destino:</strong></td>
                                          <td><span style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;margin-bottom: 10px;font-weight: normal;font-size: 14px;line-height: 1.6"><?php echo  utf8_decode($this->dados['destino']); ?></span></td>
                                        </tr>
                                        <tr>
                                          <td><strong>Descri&ccedil;&atilde;o:</strong></td>
                                          <td><span style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;margin-bottom: 10px;font-weight: normal;font-size: 14px;line-height: 1.6"><?php echo  utf8_decode($this->dados['adicional']); ?></span></td>
                                        </tr>
                                      </table>
                          </div></td></tr></table></div><!-- /content -->





                    <!-- content -->

                    <div class="content" style="margin: 0 auto;padding: 15px;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;max-width: 600px;display: block"><table bgcolor="" style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;width: 100%"><tr style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif"><td style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif">



                                    <!-- Callout Panel -->

                                    <p class="callout" style="margin: 0;padding: 15px;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;background-color: #ECF8FF;margin-bottom: 15px;font-weight: normal;font-size: 14px;line-height: 1.6"><a href="#" target="_blank" style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif;color: #2BA6CB;font-weight: bold">http:// <?php echo $_SERVER['HTTP_HOST'];?></a>  </p><!-- /callout panel -->



                                </td>

                            </tr></table></div><!-- /content -->



                </td>

                <td width="5%" bgcolor="#FFFFFF" style="margin: 0;padding: 0;font-family: &quot;Helvetica Neue&quot;, &quot;Helvetica&quot;, Helvetica, Arial, sans-serif"></td>

            </tr></table><!-- /BODY --></body>

</html>

