<div class="button-group filter-button-group">
    <button id="voltar">Voltar</button>
</div>

    <div class="portfolio-grids">
        <? if ($this->galerias) { ?>
            <? foreach ($this->galerias as $galeria) { ?>
                <a href="<?= $this->url(array('controller' => 'galeria', 'action' => 'dados', 'param' => $galeria['id']), 'default', TRUE); ?>" class="b-link-stripe b-animate-go"  title="">
                    <div class="view view-ninth">
                        <img src="<?= $this->BaseUrl('imagens/galerias/' . $galeria['imagem']); ?>" />
                        <div class="mask mask-1"></div>
                        <div class="mask mask-2"></div>
                        <div class="content">
                            <h2><?= $galeria['nome']; ?></h2>
                            <p><?= $this->LimitaTexto(strip_tags($galeria['descricao']), 150); ?></p>
                            <a href="#" class="info">Ver Mais...</a>
                        </div>
                    </div>
                </a>
            <? } ?>
        <? } else { ?>
        <BR>
        <BR>
            <div class="alert alert-danger" role="alert"><span class="glyphicon" aria-hidden="true"></span><span class="sr-only">Erro:</span>Não há registro de veículos para venda, na base de dados!</div>
        <? } ?>

    </div>
    <div class="clearfix"> </div>


