<div class="port">
    <div class="button-group filter-button-group">
        <button data-filter="*" class="clicado">Todas Operações</button>
        <button data-filter=".2">Operação Suínos</button>
        <button data-filter=".1">Operação Granel</button>
    </div>

    <div class="portfolio-grids">    
        <? if($this->galerias){ ?>
        <? foreach($this->galerias as $key => $galeria){?>
        <div class="<?=$galeria['operacao'];?>">
        <a href="<?=$this->url(array('controller'=>'galeria', 'action'=>'dados', 'param' => $galeria['id']),'default', TRUE);?>" class="b-link-stripe b-animate-go"  title="">
            <div class="view view-ninth">
                <img src="<?=$this->BaseUrl('imagens/galerias/'.$galeria['imagem']); ?>"/>
                <div class="mask mask-1"></div>
                <div class="mask mask-2"></div>
                <div class="content">
                    <h2><?=$galeria['nome'];?></h2>
                    <p><?=$this->LimitaTexto(strip_tags($galeria['descricao']),150);?></p>
                    <a href="#" class="info">Ver Mais...</a>
                </div>
            </div>
        </a>
        </div>
        <? } ?>
        <? }else{ ?>
           <span class="label label-warning">Não há registro na base de dados!</span>
        <? }?>

    </div>
            <div class="clearfix"> </div>
</div>
