<?php
$this->headLink()->appendStylesheet($this->BaseUrl('assets/js/bxslider/jquery.bxslider.css'));
$this->headScript()->appendFile($this->BaseUrl('assets/js/bxslider/jquery.bxslider.min.js'));
$this->headLink()->appendStylesheet($this->BaseUrl('assets/css/veiculo.css'));
$this->headScript()->appendFile($this->BaseUrl('assets/js/veiculo.js'));
?>
<div class="blog">
    <div class="blog-left">
        <div class="blog-left-info">
            <h3><?= $this->dados['marca'] ?> <?= $this->dados['modelo'] ?></h3>
            <? if ($this->dados['imagens']) { ?>
                <ul class="venda">
                    <? foreach ($this->dados['imagens'] as $imagem) { ?>
                        <li>
                            <img class="img-thumbnail" src="<?= $this->Img('imagens/vendas/' . $imagem['imagem'], 1500, 740); ?>" title="<?= $this->dados['marca'] ?> <?= $this->dados['modelo'] ?>" alt="<?= $this->dados['marca'] ?> <?= $this->dados['modelo'] ?>">
                        </li>
                    <? } ?>
                </ul> 
                <div id="bx-pager">
                    <? foreach ($this->dados['imagens'] as $key => $imagem) { ?>
                        <a data-slide-index="<?= $key ?>" href="">
                            <img class="img-thumbnail" src="<?= $this->Img('imagens/vendas/' . $imagem['imagem'], 80, 80); ?>"/>
                        </a>
                    <? } ?>
                </div>
            <? } ?>
            <div class="buy">
                <div class="buy-text">
                    <h3><?= $this->dados['marca'] ?> <?= $this->dados['modelo'] ?></h3>
                    <ul class="list-group">
                        <li class="list-group-item">
                            COR:
                            <?= $this->dados['cor']; ?>   
                        </li>
                        <li class="list-group-item">
                            ANO:
                            <?= $this->dados['ano'] ?>
                        </li>
                        <li class="list-group-item">
                            CÂMBIO:
                            <?= $this->dados['cambio']; ?>   
                        </li>
                        <li class="list-group-item">
                            TIPO: <?= $this->dados['tipo']; ?>
                        </li>
                        <li class="list-group-item">
                            KM:<?= number_format($this->dados['km_rodados'], 2, ",", "."); ?>     
                        </li>

                        <li class="list-group-item">
                            VALOR:
                            R$ <?= number_format($this->dados['valor'], 2, ",", "."); ?>     
                        </li>
                    </ul>
                    <div><?= $this->dados['descricao'] ?></div>
                </div>

                <div class="clearfix"> </div>
                <div class="buy-now">
                    <a href="#formProposta" rel="modal:open" class="hvr-bounce-to-left">Fazer Proposta</a>

                </div>
                <div class="clearfix"> </div>
            </div>
        </div>  
    </div>   
    <div class="clearfix"> </div>   
</div>

<!-- Modal HTML embedded directly into document -->
<form action="<?= $this->url(array('controller' => 'vendas', 'action' => 'proposta'), 'default', TRUE); ?>" method="post" class="login_form modal" id="formProposta" style="display:none;">
    <h3>FAZER PROPOSTA</h3>
    <p><input  type="hidden" name="param" value="<?= $this->dados['id'] ?>" /></p>
    <p><input  placeholder="Seu Nome" type="text" class="form-control" name="nome" required/></p>
    <p><input  placeholder="Seu E-mail" type="text" class="form-control" name="email" /></p>
    <p><input  placeholder="Seu Telefone" type="text" class="form-control" name="telefone" maxlength="14" onkeypress="mascara(this)" required /></p>
    <p><textarea placeholder="Deixe uma Mensagem" rows="8" class="form-control" name="mensagem" required></textarea></p>
    <p><input type="submit"  class="btn btn-success right" value="Enviar" /></p>
</form>

