<!-- footer-top -->
<div class="footer-top">
    <div class="footer-top-grid">
        <h3><span>MISSÃO</span></h3>
        <p><?=$this->missao['conteudo'];?></p>
    </div>

    <div class="footer-top-grid">
        <h3><span>VISÃO</span></h3>
        <p><?=$this->visao['conteudo'];?></p>
    </div>

    <div class="footer-top-grid">
        <h3><span>VALORES</span></h3>
        <div class="unorder">
            <?=$this->valores['conteudo'];?>
        </div>
    </div>
    <div class="footer-top-grid">
        <h3> <span>FALE CONOSCO</span></h3>
        <ul class="twi">
        	<li><a href="mailto:op.granel@piglog.com.br" class="mail">OPERAÇÃO GRANEL</a></li>
            <li><a href="mailto:op.suinos@piglog.com.br" class="mail">OPERAÇÃO SUÍNOS</a> </li>
            
            
        </ul>
        <ul class="twi">
        	<li><a href="mailto:administrativo@piglog.com.br" class="mail">ADMINISTRATIVO</a></li>
           <li><a href="mailto:gerencia@piglog.com.br" class="mail">GERÊNCIA</a></li>
            
        </ul>
    </div>
    <div class="clearfix"> </div>
</div>
<!-- //footer-top -->
<!-- footer -->
<div class="footer">
    <div class="footer-left">
        <ul>
                <li><a href="/">
                        <img src="<?=$this->BaseUrl('assets/images/logo1.png');?>" alt=" " /></a><span> |</span>
                </li>
            <li><p>Copyrights © 2016. Todos os Direitos Reservados por <span> Pig Log Transportes </span></p></li>
        </ul>
    </div>
    <div class="footer-right">
<!--        <p>Desenvolvido por <a href="http://thiagocarlos.com.br/">TCS</a></p>-->
    </div>
    <div class="clearfix"> </div>
</div>
<!-- //footer -->